### ISSUE TITLE
attr_accessor method and arguments

### ISSUE THREAD

**Issue by simoncal-saas** [RailsApps/learn-rails#102]
Issues applicable with code and Book Two Version 4.1.0:

1)
:string should be removed from 5 attr_accessor Ruby statements.  For example,
**attr_accessor :email, :string** should be replaced with **attr_accessor :email**

2)
attr_accessor :name, :string
attr_accessor :email, :string
attr_accessor :content, :string

can be combined into one statement:
**attr_accessor :name, :email, :content**

3)
2 sentences containing **attr_accessor keyword, specifying ........ is a string**, should be removed.

We create the email attribute using the attr_accessor keyword, ........
We create attributes (data fields) for the model by using the attr_accessor keyword, ......

**Comment by DanielKehoe** [comment]
Thanks for suggesting the improvement. I've made the change for the next edition of the book.
