### ISSUE TITLE
Welcome messages via MailChimp

### ISSUE THREAD

**Issue by simoncal-saas** [RailsApps/learn-rails#103]
In Book II Version 4.1.0, Chapter 21 Mailing List, Section "Test the Application", it is unclear how welcome messages are **automatically** delivered to mail list subscriber.

I've been unsuccessful in initiating auto e-mails to subscribers, following MailChimp's "Double Opt-in Process" at http://kb.mailchimp.com/lists/signup-forms/about-double-opt-in.

l've been able to send out e-mails to subscribers via MailChimp Campaigns, given the lengthy instructions.

**Comment by DanielKehoe** [comment]
The book currently contains the instructions...
```
It's a bit difficult to find the MailChimp option to create a welcome
message. Strangely, MailChimp considers a welcome message a "form."
Here's how to find it. On the MailChimp "Lists" page, click the "down
arrow" for a list and click "Signup forms." Then click "General forms."
On the "Create Forms" page, there is a drop-down list of "Forms &
Response Emails." The gray box shows "Signup form." Click the down
arrow. Select the menu item named "Final 'Welcome' Email" and you'll be
able to create a welcome message.
```
Does this not work to add a welcome message? The instructions match the (complicated) MailChimp interface. I haven't recently tested the welcome email feature. Did it not work?

**Comment by simoncal-saas** [comment]
I probably misunderstood the MailChimp process.  Apparently, a welcome message will be delivered to list subscribers after e-mail content is created via some type of forms, and triggered by Campaign or Automation.  Closed as 'not an issue' of Learn Ruby on Rails: Book Two.
