### ISSUE TITLE
Broken link, mini-test Capybara Expectation

### ISSUE THREAD

**Issue by simoncal-saas** [RailsApps/learn-rails#104]
In Book II Version 4.1.0, Chapter 24, Testing/Feature Test/Scenario:

[documentation for Capybara expectations](https://www.omniref.com/ruby/gems/minitest-capybara/0.7.1/symbols/Capybara::Expectations#tab=Methods) link is broken.

[documentation for Capybara expectations](http://blowmage.com/minitest-rails-capybara/Capybara/Expectations.html) works.

**Comment by DanielKehoe** [comment]
Thanks for finding this error. No one else caught it. The next edition of the book will include the correction.

I appreciate your efforts to improve the book.
