### ISSUE TITLE
Diagrams are missing from MVC section in chapter 12

### ISSUE THREAD

**Issue by lhcamilo** [RailsApps/learn-rails#106]
The text refers to diagrams but there are none to be found.

Correction: the diagrams are at the very end of the chapter

**Comment by DanielKehoe** [comment]
I'm looking at the online edition at
https://tutorials.railsapps.org/books/learn-rails-2#cid83
and the diagrams are in place. Which format or version are you using? There is PDF and ebook as well as online versions at https://tutorials.railsapps.org/ and http://learn-rails.com/.

**Comment by lhcamilo** [comment]
Sorry, should have made it clear. I am referring to the pdf version.
