### ISSUE TITLE
Installing rvm on Nitrous.io

### ISSUE THREAD

**Issue by railspadawan** [RailsApps/learn-rails#42]
Hello Daniel,
     i have followed the 3 steps to install rvm on Nitrous:
1) Uninstall chruby 
2) $ \curl -L https://get.rvm.io | bash -s stable --auto-dotfiles --ruby
3) source /home/action/.rvm/scripts/rvm
   I get the error message  "-bash: /home/action/.rvm/scripts/rvm: No such file or directory"
 I checked home/action/.rvm and the directory scripts is not present. 

Could you help me here?
shalini

**Comment by Saramoshggoo** [comment]
Hi daniel 
Could you tell me the command code for part 3?
Thanks 
Sara
