### ISSUE TITLE
Contact Form > Model page 201

### ISSUE THREAD

**Issue by JStuart15** [RailsApps/learn-rails#46]
Hi Daniel,
 Thanks for your tutorial, it was the only thing that kept me from giving up on Rails.

  On page 201, I received an error with the following code:

validates_format_of :email,
:with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  I was able to work around it using a tool you recommended (Dash) with the following:

validates_format_of :email, with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  Thanks again for all you do to help the beginners.
Jeff

**Comment by DanielKehoe** [comment]
Thanks for bringing this to my attention.

Thanks for the kind words, too.
