### ISSUE TITLE
Dynamic Home Page chapter

### ISSUE THREAD

**Issue by hewydewyle** [RailsApps/learn-rails#47]
the page wont load on the localhost, upon making the visitors_controllers and etc.

ActionView::MissingTemplate at /
Missing template visitor/new with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/Users/hieu/.rbenv/versions/2.2.0-dev/lib/ruby/gems/2.3.0/gems/web-console-2.0.0/lib/action_dispatch/templates"
  * "/Users/hieu/railsapp/learn-rails/app/views"
  * "/Users/hieu/.rbenv/versions/2.2.0-dev/lib/ruby/gems/2.3.0/gems/foundation-rails-5.5.1.0/app/views"

**Comment by DanielKehoe** [comment]
Do you have a file *learn-rails/app/views/visitor/new.html.erb*?
