### ISSUE TITLE
Giving a 'test drive' to the app before following the book.

### ISSUE THREAD

**Issue by serodriguez68** [RailsApps/learn-rails#48]
Hi Daniel!  
I've been following along with the book and I'm very grateful for your work.
I wanted to give the app a test drive before continuing to better understand where I'm heading to, however I'm not sure how to do this (given the fact that I'm just beginning the book).

I forked your "learn-rails" and cloned it into my mac with the name "learn-rails-guide" (as "learn-rails" was already taken for following along). When tried to start the server, I got an error saying that I should run 'bundle install'. 

I did so hoping that the gemset created during the following along won't get messed up; however 'bundle' wasn't able to install the 'pg' gem. And I hit a road block...

Am I taking the wrong approach for trying the finished app locally?
Will an app with a .ruby-gemset and a .ruby-version files mess up my current gemsets?

Thanks!

**Comment by DanielKehoe** [comment]
try ```$ bundle install --without production``` (see the book's deploy chapter).

You should be able to run the app locally after cloning from the repo. However, I feel you'll gain little benefit versus simply following the book.

**Comment by serodriguez68** [comment]
Thanks for the quick response!

Is changing the name of the root folder an issue?
