### ISSUE TITLE
running command "rails generate layout:install foundation5 --force"

### ISSUE THREAD

**Issue by zeallous** [RailsApps/learn-rails#52]
following your book, I ran the command above.

i got this

Sass::SyntaxError at /
Invalid CSS after "...ules: $modules ": expected "}", was "!global;"
  (in /Users/ansonzeall/Dropbox/rails/learn-rails/app/assets/stylesheets/framework_and_overrides.css.scss:13)

**Comment by DanielKehoe** [comment]
How were you able to resolve the issue? It will help others if you can share the solution. Thanks.
