### ISSUE TITLE
Trying to run Rails composer but running into problems

### ISSUE THREAD

**Issue by zeallous** [RailsApps/learn-rails#54]
Just trying to run the demo app ...compiling...and getting this:

On branch master
nothing to commit, working directory clean
    composer  Stage Three (running recipe 'stage_three' callbacks).
learn_rails
  learn_rails  recipe stage three
      remove    app/models/contact.rb

and errors all below

**Comment by DanielKehoe** [comment]
What are the errors? You haven't provided the error output. If it's an issue with Rails Composer, you should open an issue elsewhere: https://github.com/RailsApps/rails-composer/issues
