### ISSUE TITLE
segmentio.js API key as an environment variable

### ISSUE THREAD

**Issue by JaneJieYing** [RailsApps/learn-rails#56]
Hi! Thanks for the awesome tutorial.

I have just completed the chapter on Analytics and I successfully got Segment and Google Analytics to display visitors' data for me.

However, I would like to store the Segment API Write Key in my application.yml file instead of putting it in segmentio.js. I tried the following two but both did not work. 

window.analytics.load('ENV["SEGMENT_API_KEY"]');
window.analytics.load(ENV["SEGMENT_API_KEY"]);

Any advice?

**Comment by DanielKehoe** [comment]
JavaScript files (ending in ".js") run in the user's browser, so the environment variables from the server are not available. You could take a look at [Railscast 3324](http://railscasts.com/episodes/324-passing-data-to-javascript) to see several ways to pass variables from a Rails application to JavaScript.

**Comment by JaneJieYing** [comment]
Thanks Daniel! I will try it.
