### ISSUE TITLE
cannot 'rake secrets' to create secret_key_base?

### ISSUE THREAD

**Issue by Chris-Manalo** [RailsApps/learn-rails#57]
I am on a windows 8.1 machine and I am using the figaro gem to set env. variables but I cannot create the key with 'rake secret'
wrong gem?
wrong approach?

**Comment by DanielKehoe** [comment]
Please see the most recent edition of the book [Learn Ruby on Rails](http://learn-rails.com/learn-ruby-on-rails.html). I no longer recommend the Figaro gem (use *secrets.yml* instead). And I don't advise learning on Windows (use a VM or Nitrous.io).
