### ISSUE TITLE
Git problems

### ISSUE THREAD

**Issue by thomasbakp** [RailsApps/learn-rails#58]
In the first GIT chapter when I enter command  git push -u origin master I get: remote: Repository not found.
fatal: repository 'https://github.com/YOUR_GITHUB_ACCOUNT/learn-rails.git/' not found
I have entered name and password in GIT but the first time I accidentally entered the line with YOUR_Github_account....
Does this has anything to do with that now the Repository not found?

**Comment by DanielKehoe** [comment]
That could be the problem. Fix the name in Git and please report back if that resolves the issue.

**Comment by thomasrap** [comment]
I did fix the name in GIT but no change...hmmm. What is it that I am not seeing

**Comment by DanielKehoe** [comment]
Did you resolve this issue?

**Comment by thomasbakp** [comment]
Yes. I erased previous installed version of learn-rails.
However I couldnt push with command:  git push -u origin master.
I got:
! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/thomasbakp/learn-rails.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I checked stackoverflow and used:  git push origin +HEAD
And it pushed the code.
Maybe you want to use it for updated version?

**Comment by DanielKehoe** [comment]
I've mentioned this problem in the newest edition of the book and linked back here.

**Comment by Massiff** [comment]
In my case problem was in missed step on creating repo in my github account.

**Comment by DanielKehoe** [comment]
Here's what you need to know.

If you blindly copy and paste the command shown in the book:

```
git remote add origin https://github.com/YOUR_GITHUB_ACCOUNT/learn-rails.git
```
You have told git that there is a repo named YOUR_GITHUB_ACCOUNT on GitHub.

So try this:

```
$ git remote show
origin
$ git remote remove origin
$ git remote show
```
That will reverse the problem you created. Then you can go back to the book and follow the steps again to add GitHub as a remote repository for your project.
