### ISSUE TITLE
 Gibbon::MailChimpError at /visitors  Invalid MailChimp List ID: Learn Rails Newsletter

### ISSUE THREAD

**Issue by Chris-Manalo** [RailsApps/learn-rails#59]
I can see the API calls in my mailchimp account, and I am certain I have the name of the newsletter correct that I created. And I have tried quotes around the newsletter and under_scores, but I am still getting the error. What else could be going wrong?

**Comment by DanielKehoe** [comment]
Were you able to resolve this issue? What fixed it?

**Comment by DanielKehoe** [comment]
Closing the issue as no reply.

**Comment by DMH007** [comment]
Hey Daniel,

I keep getting the following message whenever I attempt to request for the newsletter.  My API information is already entered: You must set an api_key prior to making a call. Any help would be appreciated....

**Comment by DanielKehoe** [comment]
Add a line of debugging code to make sure you are actually passing the api key:

```
  def subscribe
    mailchimp = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)
    Rails.logger.info "api_key is #{Rails.application.secrets.mailchimp_api_key}"
```

Then check your console log to see if the api key is actually logged.

**Comment by DMH007** [comment]
Cool!
