### ISSUE TITLE
Missing `secret_token` and `secret_key_base` for 'development' environment

### ISSUE THREAD

**Issue by davefogo** [RailsApps/learn-rails#60]
Dear Daniel,

I am following your tutorial book "Learn Rails" through the RailsApps Tutorial program (great work by the way!). I am stuck at the send mail chapter.
I encounter an Internal Server Error:

`Missing `secret_token` and `secret_key_base` for 'development' environment, set these values in `config/secrets.yml`
WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26) at localhost:3000. `

I have tried reseting the secret key base using rake secret and changing it in both environment and secrets file with no success. 

Thank you!

**Comment by DanielKehoe** [comment]
Were you able to resolve this issue?

**Comment by davefogo** [comment]
Nope. I had to continue with hard coded credentials for this to work.

**Comment by DanielKehoe** [comment]
Closing the issue as it seems to be a local configuration issue. Will reopen if anyone else reports this issue.

**Comment by Sheetalprasad** [comment]
Even I am also facing the same problem Deniel, 
Internal Server Error

Missing `secret_token` and `secret_key_base` for 'development' environment, set these values in `config/secrets.yml`
WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13) at 92ds6d57.ngrok.io:443
What should I do to solve this issue

**Comment by AnnaRedziak** [comment]
I have exactly the same problem:
#<RuntimeError: Missing `secret_key_base` for 'development' environment, set this value in `config/secrets.yml`>

I tried many things, nothing what I do helps. Any idea what could I try to make it work? 

## update 
It worked when I added following line to the application.rb
config.secret_key_base = '<%= ENV["SECRET_KEY_BASE"] %>'

**Comment by zismailov** [comment]
> config.secret_key_base = '<%= ENV["SECRET_KEY_BASE"] %>'

it also worked for me

**Comment by belalelmi** [comment]
2022 and it's still working, good stuff
