### ISSUE TITLE
Error “An SMTP To address is required to send a message” in "Send Mail" section

### ISSUE THREAD

**Issue by floalex** [RailsApps/learn-rails#64]
I keep getting this error when using Gmail account.  When I switched to my other email address, the issue went away. 

I also posted on http://stackoverflow.com/questions/31888911/error-an-smtp-to-address-is-required-to-send-a-message-on-learn-rails-tutorial

**Comment by dannypernik** [comment]
I'm also getting this error. Hoping for another response on the SO question.

**Comment by sarah-kallansrud** [comment]
Has anyone figured this out? I've tried a lot of different things, including hardcoding the info into secrets.yml and I keep getting this same error.

**Comment by suzybirmingham** [comment]
I have also been stumped by this error. I've tried hardcoding my user info in secrets.yml, using an alternate Gmail address, and installing the figaro gem as a different way to handle env. variables. I;m stumped!

**Comment by dapperAuteur** [comment]
just got this error. Any updates other than hard coding your info into secrets.yml?

**Comment by FNGR2911** [comment]
samehere.

**Comment by DanielKehoe** [comment]
If it works by hardcoding the credentials in the secrets.yml file, then the application is working as it should. Any other problems are issues with your local environment variables and Unix shell, and that is beyond the scope of the book, as these issues are specific to your computer.

**Comment by FNGR2911** [comment]
Yes, you're right. Maybe somebody can find a solution ;) I think this issue should be closed.

**Comment by gauntlett** [comment]
I had this same problem, and after a bit of trial and error figured out the problem. Well, this worked for me...

I had been running the rails server in a console window that had been open a while. Restarting the server with a cntl ^c, and then 'rails server' didn't solve anything. So, I went through my exports in .bash_profile where everything looked good. I had the following, but with my information filled in.

export MANDRILL_USERNAME="example@example.com"
export MANDRILL_API_KEY="Your_Mandrill_API_Key"
export MAILCHIMP_API_KEY="Your_MailChimp_API_Key"
export MAILCHIMP_LIST_ID="Your_List_ID"
export OWNER_EMAIL="example@example.com"

Then I tried 'source .bash_profile' to reload the environment.
'echo $OWNER_EMAIL' was working as it should

What I finally realized is that the ruby application wasn't seeing the environment variables. To check you can run irb and see if the variables are available to the app.

For example:
'irb'
'ENV["OWNER_EMAIL"]' -- This should show you the owner email you have set in your .bash_profile if you get nil then ruby isn't seeing your environment variables and your environment needs reloading.

**So... It finally occurred to me that perhaps I need to reload the environment in the console window that I was running the rails server. I ran 'source .bash_profile' then did 'rails server' and it worked!**

You could also just close that window and open a new one, which would automatically reload your environment variables.

I hope this helps!

**Comment by FNGR2911** [comment]
that sounds really good @gauntlett! I'll give it a try later and will post if it works! thank you very much.

**Comment by FNGR2911** [comment]
That works for me!! Awesome! I think this answer should be added to the tutotial as a Link for people having trouble. What do you think @DanielKehoe ?

**Comment by gauntlett** [comment]
Glad to hear it worked out for you!

**Comment by DanielKehoe** [comment]
I've updated the book to add a tip about reopening the terminal window.

Incidentally we now use SendGrid instead of Gmail or Mandrill. Mandrill dropped the free trial offer.
