### ISSUE TITLE
Error while creating the “foobar-kadigan” application

### ISSUE THREAD

**Issue by asalom** [RailsApps/learn-rails#66]
I encountered an error while running the command to create the application from the rails composer templates. The command I used was:
```
rails new foobar-kadigan -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb
```

After choosing all options as required in the book, the command failed with the following error:
```
dyld: Symbol not found: _rb_ary_new_from_values
```

[The solution] (http://stackoverflow.com/a/24910772/1266056) is to install ```foreman``` before creating the application
```
gem install foreman
```

**Comment by DanielKehoe** [comment]
Seems like it might be a local configuration issue. There really should be no need to install Foreman to generate the app. In any case, the issue is more appropriate for the Rails Composer repo issues.
