### ISSUE TITLE
 GoogleDriveV0.login is deprecated and will be removed in the next version. Use GoogleDriveV0.login_with_oauth instead.

### ISSUE THREAD

**Issue by patsiren** [RailsApps/learn-rails#69]
The google_drive v0 gem uses a call to ../ClientLogin to verify app credentials, which was officially deprecated as of April 20, 2015 and removed by google (see: https://developers.google.com/api-client-library/java/google-api-java-client/client-login).  Calls to ClientLogin now return a 404 error.

Use of the v0 gem requires you to use GoogleDriveV0.login_with_oauth.  Setting up an application-specific password does not resolve this issue.

Console error here:

WARNING: GoogleDriveV0.login is deprecated and will be removed in the next version. Use GoogleDriveV0.login_with_oauth instead.
Completed 500 Internal Server Error in 174ms

GoogleDriveV0::AuthenticationError - Authentication failed for [REDACTED: USERNAME]: Response code 404 for post https://www.google.com/accounts/ClientLogin: https://developers.google.com/accounts/docs/AuthForInstalledApps

**Comment by patsiren** [comment]
For instructions on implementing the google_drive gem, upgrade to v1.0.1 and see: https://github.com/gimite/google-drive-ruby

**Comment by DanielKehoe** [comment]
@patsiren: It seems you are working from an outdated version of the book. Be sure you have book v2.2.0.

I've addressed this issue previously: https://github.com/RailsApps/learn-rails/issues/51

Google now requires use of OAuth 2.0 for application access to Google Drive. The implementation is considerably more complex than the previous implementation using a Gmail address and password. I’ve released a new version of the book (version 2.2.0 now available on Amazon and online at learn-rails.com) and have dropped the “Spreadsheet Connection” chapter. I'm sure this will be disappointing but the chapter was primarily about adding a "fun feature" and doesn't diminish the value of the tutorial.

There is no longer an easy way (for beginners) to authenticate for access to Google Drive.

**Comment by patsiren** [comment]
Hi Daniel,

Thanks for the clarification. Though, I've been accessing the online
version of the book through the tutorials.railsapps index - is there a
different way to access the latest version of the book online or are only
the Kindle/EPub editions current

Thanks,

PS

**Comment by DanielKehoe** [comment]
My bad. And my apologies. Thanks for bringing it my attention. I neglected to update the version at tutorials.railsapps.org. And that is supposed to be the definitive edition. Just generated and deployed the update now.

**Comment by patsiren** [comment]
No worries, thanks for the quick response and pushing the update! I'm
looking forward to getting back to it :)

Best,

Patrick
