### ISSUE TITLE
secrets.yml : commits with secret key

### ISSUE THREAD

**Issue by Nuttdguy** [RailsApps/learn-rails#70]
I made a mistake including application.yml which contained my email and password. Upon discovery, I noticed that the secret token in secrets.yml was also disclosed; which made me wonder if that file was suppose to an exclusion file within the git configuration. Can someone clarify if that's suppose to excluded with commits?

**Comment by DanielKehoe** [comment]
It should not matter if the development `secret_key_base` in the *config/secrets.yml* is disclosed. Someone would need access to your local machine running in development mode and there shouldn't be anything to compromise in development mode, anyway. Don't put any credentials in the *config/secrets.yml*, just use Unix environment variables.
