### ISSUE TITLE
Error when i try to submit the info in my contact form

### ISSUE THREAD

**Issue by mareSLO** [RailsApps/learn-rails#71]
Hello guys, hope someone can help. Basically when i click the submit button, to test if the form is working, so i could actually receive an email, i get this.

![screenshot from 2015-10-07 02 36 51](https://cloud.githubusercontent.com/assets/11389588/10326523/8e98dc98-6c9c-11e5-9312-e6c2947bd20d.png)
.

**Comment by DanielKehoe** [comment]
Did you create a file *app/views/user_mailer/contact_email.html.erb*?

**Comment by DanielKehoe** [comment]
Closing this issue as no response and not reported by anyone else.
