### ISSUE TITLE
Git remote repository

### ISSUE THREAD

**Issue by paultassi** [RailsApps/learn-rails#72]
Hello Daniel,

I still get this error when git pushing:
''Everything up-to-date
fatal: '=' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.''

That's strange because on Github, my project is up-to-date with changes in command line... It seems like he is pushing to Github...

When I put git remote -v
"origin	https://github.com/paultassi/learn-rails.git (fetch)
origin	https://github.com/paultassi/learn-rails.git (push)
origin	= (push)"

Can you help me clarifying/fixing this?

Thank you

**Comment by DanielKehoe** [comment]
It's not a problem with the learn-rails application. Rather, it is a local configuration issue, or yoru error in following the instructions in the book, so I'm sorry but I can't solve the problem for you.

I suggest you start building the application again, following the instructions carefully.
