### ISSUE TITLE
PG::ConnectionBad

### ISSUE THREAD

**Issue by dapperAuteur** [RailsApps/learn-rails#74]
I'm using the Rails Signup & Download tutorial but trying to set it up to deploy to heroku for production.
I received the error when attempting to preview the app using 'rails s -p $PORT -b $IP.
What went wrong?
Below are the choices I made setting up the app using composer:
Web server for development? WEBrick (default)
Web server for production? Unicorn
Database used in development? postgresql
Template engine? ERB
Test framework? RSpec with Capybara
Continuous testing? Guard
Front-end framework? Bootstrap 3.3
Add support for sending email? Gmail
Devise modules? Devise with default modules
Admin interface for database? Upmin
Use a form builder gem? SimpleForm
Install page-view analytics? Google Analystics
Prepare for deployment? yes
Set a robots.txt file to ban spiders? no
Create a GitHub repository? no
Use or create a project-specific rvm gemset? no

**Comment by DanielKehoe** [comment]
These issues are for the repo for the 'learn-rails' example application, for the [Learn Ruby on Rails](http://learn-rails.com/learn-ruby-on-rails.html) book. Use the issues in the repo for [rails-signup-download](https://github.com/RailsApps/rails-signup-download) application.
