### ISSUE TITLE
Zurb Foundation 6 not supported

### ISSUE THREAD

**Issue by Westopher** [RailsApps/learn-rails#79]
Every time I get to the point where the the Zurb gem is utilized (The step in the tutorial is entitled: Rails Layout Gem with Zurb Foundation), I get the error:

".column" failed to @extend ".small-6".
The selector ".small-6" was not found.
Use "@extend .small-6 !optional" if the extend should be able to fail.

I've followed the tutorial to the T up until now and had the same error even after starting over. So I'm not sure what is wrong. If I remove the styling, the whole site looks like hell. I'm not sure what to do. Does anyone else get this error? How did you solve it?

**Comment by DanielKehoe** [comment]
Zurb Foundation 6 is now out. It is not compatible with Zurb Foundation 5. Zurb has not yet published a migration guide or documentation for converting from Zurb Foundation 5 to 6.

We'll continue to use Zurb Foundation 5 in this tutorial and application. That requires specifying the older version in the Gemfile:

```
gem 'foundation-rails', '~> 5.5'
```
As described in the book, the "squiggle" operator means use “pessimistic” versioning. It means use any version greater than 5.5 and less than 6.0.

**Comment by key2me** [comment]
thanks, kinda helpful!!
