### ISSUE TITLE
Newer versions of foundation-rails are incompatible with the tutorial 

### ISSUE THREAD

**Issue by williamseipp** [RailsApps/learn-rails#81]
I was using foundation-rails ( 6.1.2.0 ) and could not finish the end of Chapter 16, specifically navigating to the home page.

Error in browser reads ".column failed to @extend ".small-6". The selector ".small-6 was not found. Use "@extend. small-6 !optional" if the extend should fail

my editor indicated that the foundation css was not being imported or was unreadable.

I downgraded the foundation-rails gem from 6.1.2.0 to 5.5.3.2 as listed in this repository and I was able to load the page just fine.

**Comment by DanielKehoe** [comment]
Already reported, see https://github.com/RailsApps/learn-rails/issues/79

The newest version of the book, version 3.0.1, has been updated to address this issue.

**Comment by williamseipp** [comment]
I found #79 minutes after reporting, sorry for the trouble!

Fantastic tutorial btw thank you so much for writing it and giving CONTEXT
for new guys like me.

**Comment by DanielKehoe** [comment]
No problem, glad you took the trouble to open an issue, even if it's a duplicate it helps people find it.

Thanks for the kind words.
