### ISSUE TITLE
Cloud9 Changed Custom Workspace to now called Blank Workspace

### ISSUE THREAD

**Issue by RemeberMe** [RailsApps/learn-rails#87]
In the infinite wisdom, Cloud9 changed from calling their Custom Workspace to Blank Workspace.  I guess they were bored that day.

**Comment by DanielKehoe** [comment]
Thanks for the update.

Cloud9 :-(

I’ll revise the book.

It’s feedback like yours that helps out everyone

-- 
Daniel Kehoe
daniel@danielkehoe.com
https://twitter.com/rails_apps

**Comment by RemeberMe** [comment]
You have a great tutorial!  It's more like how Ruby on Rails is a system. It hooks a lot of learning together such as Github, Git, Linux, etc, which makes it far more valuable than just learning Ruby or another language alone.  I've been struggling to learn how version control, linux, Github, and the rest work and this throws me right into the usage without all the dry reading. Thanks for the time and effort you took!  

Finding these issues is really increasing my understanding of how things work.  I almost hate to see the problems taken out, because like you know, people learn more when they are forced to figure it out, and that's what programming is all about :)
 Hal

**Comment by kwibus2000** [comment]
Dear Daniel Kehoe,

May I ask you why you dislike Cloud9?  [quote Cloud9:-( unqoute]
I use it some weeks now, and I like it!

Best Regards,
Ad

**Comment by DanielKehoe** [comment]
I was just whining that Cloud9 changed a name of a feature (calling their Custom Workspace to Blank Workspace) which created confusion. Other than that, Cloud9 is a great service.
