### ISSUE TITLE
Rails server failing to a launch after gemfile was modified.

### ISSUE THREAD

**Issue by oshybrid** [RailsApps/learn-rails#91]
Error
[error.txt](https://github.com/RailsApps/learn-rails/files/956146/error.txt)

Original Gemfile
[Gemfile_bak.txt](https://github.com/RailsApps/learn-rails/files/956158/Gemfile_bak.txt)

New Gemfile
[Gemfile_new.txt](https://github.com/RailsApps/learn-rails/files/956159/Gemfile_new.txt)

**Comment by DanielKehoe** [comment]
You removed the Rails gem from the Gemfile. You should restore it.

```
gem 'rails', '~> 5.0.2'
```

**Comment by oshybrid** [comment]
Yeah ok that was stupid of me

**Comment by oshybrid** [comment]
With the console command to see what the server up to… Where is that supposed to be invoked.  I thought you meant the console on Chrome development but the command is not taking.

**Comment by DanielKehoe** [comment]
start the server in the terminal window then watch the log scroll in the terminal window
