### ISSUE TITLE
Chapter 17 confusion

### ISSUE THREAD

**Issue by oshybrid** [RailsApps/learn-rails#94]
[Archive.zip](https://github.com/RailsApps/learn-rails/files/987118/Archive.zip)

Chapter 17 test.

Only the "Home" bar changes and shows it is part of bootstprap.
Went back over the changed files and could not see any.  Restarted the server.
Went ahead  and copy and pasted and file from PDDF to config files.  Restarted the server, still no change.
While all of this was going on.  I noticed the app/assets/javascript.js file did not have the modification of adding the entry "//= require bootstrap-sprockets" to the file after the  "rails generate layout:install bootstrap3 --force" command was run.  I added it in, saved the, restarted the server. no difference.

**Comment by oshybrid** [comment]
ALSO...
macbook-pro:learn-rails bradhutchins$ rails -v
Rails 5.0.2
macbook-pro:learn-rails bradhutchins$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
macbook-pro:learn-rails bradhutchins$

**Comment by DanielKehoe** [comment]
I've made recent changes to the rails_layout gem to accommodate Rails 5.1. The changes introduced a bug that dropped the necessary jQuery support. Try again with the latest version of the rails_layout gem.

**Comment by oshybrid** [comment]
Sure.

What is the most recent rails_layout_gem file?
Is it in an updated PDF of your book?

Sorry to be a pain.

**Comment by oshybrid** [comment]
Ok got the rails_layout gem 1.0.40 and changed Gemfile and Gemfile.lock but nothing is changing in presentation from before.

**Comment by DanielKehoe** [comment]
Closing this issue. Apparently resulting from confusion about what the application should look like in Chapter 17.
