### ISSUE TITLE
Rails 5.1 issues

### ISSUE THREAD

**Issue by oshybrid** [RailsApps/learn-rails#95]
I updated my rails_layout gem to fix a presentation problem, but that did not fix it.
So I upgraded Rails to 5.1 and fixed my Gemfile and Gemfile.lock to use 5.1 and i think I broke my gem stack.

macbook-pro:learn-rails bradhutchins$ rails s
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- erubi (LoadError)
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template/handlers/erb/erubi.rb:1:in `<top (required)>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template/handlers/erb.rb:17:in `<class:ERB>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template/handlers/erb.rb:6:in `<module:Handlers>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template/handlers/erb.rb:3:in `<class:Template>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template/handlers/erb.rb:2:in `<module:ActionView>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template/handlers/erb.rb:1:in `<top (required)>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template/handlers.rb:12:in `extended'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template.rb:110:in `extend'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template.rb:110:in `<class:Template>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template.rb:7:in `<module:ActionView>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/template.rb:5:in `<top (required)>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionview-5.1.0/lib/action_view/base.rb:7:in `<top (required)>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/actionpack-5.1.0/lib/action_dispatch/middleware/debug_exceptions.rb:5:in `<top (required)>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/web-console-3.5.0/lib/web_console/extensions.rb:44:in `<top (required)>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/web-console-3.5.0/lib/web_console/railtie.rb:10:in `block in <class:Railtie>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `run'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/bradhutchins/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/application.rb:353:in `initialize!'
	from /Users/bradhutchins/Documents/Rails/workspace/learn-rails/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:24:in `app'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:42:in `start'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:130:in `block in perform'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:125:in `tap'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/commands/server/server_command.rb:125:in `perform'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/command/base.rb:63:in `perform'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/command.rb:44:in `invoke'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/railties-5.1.0/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/bradhutchins/Documents/Rails/workspace/learn-rails/bin/rails:9:in `require'
	from /Users/bradhutchins/Documents/Rails/workspace/learn-rails/bin/rails:9:in `<top (required)>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /Users/bradhutchins/.rvm/gems/ruby-2.4.1@testing/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/bradhutchins/Documents/Rails/workspace/learn-rails/bin/spring:15:in `require'
	from /Users/bradhutchins/Documents/Rails/workspace/learn-rails/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by DanielKehoe** [comment]
Issues with Rails 5.1 resolved with 719b340d3bb42930afbfd9e7a0d85bf4a3fcf3d2
